name: Generate snake animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # generate a snake game from contributions graph
      - name: Generate contribution grid snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      # generate Metrics
      - name: Generate metrics
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          output_action: none
          config_output: svg
          user: lingbopro
          template: classic
          base: activity, community, repositories
          config_timezone: Asia/Tokyo
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_fortune: yes
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: .user.login
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
      # generate a readme file
      - name: Generate readme
        shell: bash
        run: |
          cat << EOF > dist/README.md
          # 此分支储存由 Actions 工作流生成的一些 ~~很 cool 的~~ 东西
          # 不需要关注此分支 \:P

          详情见 https://github.com/lingbopro/lingbopro/blob/main/.github/workflows/snake.yml

          ## 效果

          <picture align="center">
          <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/lingbopro/lingbopro/output/github-contribution-grid-snake-dark.svg">
          <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/lingbopro/lingbopro/output/github-contribution-grid-snake.svg">
          <img alt="GitHub contribution grid snake animation" src="https://raw.githubusercontent.com/lingbopro/lingbopro/output/github-contribution-grid-snake.svg">
          </picture>

          <img align="center" src="https://raw.githubusercontent.com/lingbopro/lingbopro/output/metrics.svg" width="400" />

          <code>:)</code>
          EOF
      # prepare
      - name: Prepare for pushing
        run: |
          echo "==== METRICS RENDERS TREE ===="
          tree /metrics_renders/
          echo "====== CURRENT DIR TREE ======"
          tree .
          echo "========== TREE END =========="
          sudo mv /metrics_renders/* ./dist
      # push the generated things to output branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: |
            Generate GitHub contribution grid snake SVG

            Auto-generated by GitHub action.
            You don't need to care.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}